using System;
using System.Collections.Generic;

namespace Warehouse.Entities
{
    public partial class ManufacturerCross
    {
        public int ManufacturerCrossId { get; set; }
        public string Item { get; set; }
        public int? Group { get; set; }
        public string Barcode { get; set; }
        public string Kap { get; set; }
        public string Kapupc { get; set; }
        public string Aimco { get; set; }
        public string Kapaimco { get; set; }
        public string ManUpc { get; set; }
        public string Pri { get; set; }
        public string Ray { get; set; }
        public string Bendix { get; set; }
        public string Wag { get; set; }
        public string Wagbd { get; set; }
        public string Napa { get; set; }
        public string Wisota { get; set; }
        public string Tomhovland { get; set; }
        public string Balkamp { get; set; }
        public string Balkampdsh { get; set; }
        public string Gbm { get; set; }
        public string Mtcad { get; set; }
        public string Vipar { get; set; }
        public string Beck { get; set; }
        public string Centric { get; set; }
        public string Auto { get; set; }
        public string Brembo { get; set; }
        public string Seymourauto { get; set; }
        public string Redstaltrw { get; set; }
        public string Midas { get; set; }
        public string Ubp { get; set; }
        public string Euro { get; set; }
        public string Raymold { get; set; }
        public string Allsafe { get; set; }
        public string MotownPart { get; set; }
        public string MotownBendix { get; set; }
        public string MotownWagner { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Plumautoparts { get; set; }
        public string Alladina { get; set; }
        public string FaKey { get; set; }
        public string AiKey { get; set; }
        public string AiUpc { get; set; }
        public string Oem { get; set; }
        public string Hollan { get; set; }
        public string Reliab { get; set; }
        public string Ipi { get; set; }
        public string Eis { get; set; }
        public string Delcoe { get; set; }
        public string Delcode { get; set; }
        public string Delcodi { get; set; }
        public string Qualit { get; set; }
        public string Spi { get; set; }
        public string Spe { get; set; }
        public string Cuc { get; set; }
        public string Climat { get; set; }
        public string Modine { get; set; }
        public string Godan { get; set; }
        public string Csf { get; set; }
        public string Amex { get; set; }
        public string Acf { get; set; }
        public string Valeo { get; set; }
        public string Tires { get; set; }
        public string Kapax { get; set; }
        public string Cct { get; set; }
        public string Adi { get; set; }
        public string Mev { get; set; }
        public string Ari { get; set; }
        public string Adl { get; set; }
        public string Cardone { get; set; }
        public string Surtrack { get; set; }
        public string Newcardone { get; set; }
        public string Crown { get; set; }
        public string Crs { get; set; }
        public string Dss { get; set; }
        public string Fenco { get; set; }
        public string Redatech { get; set; }
        public string Rockford { get; set; }
        public string Driveplus { get; set; }
        public string Wolverine { get; set; }
        public string Usa { get; set; }
        public string Summer { get; set; }
        public string Powerline { get; set; }
        public string Gsp { get; set; }
        public string GspNa { get; set; }
        public string Carquest { get; set; }
        public string Industries { get; set; }
        public string Arc { get; set; }
        public string Ammex { get; set; }
        public string Precision { get; set; }
        public string CvUnlimited { get; set; }
        public string Dns { get; set; }
        public string Lizhong { get; set; }
        public string Moog { get; set; }
        public string Chasselect { get; set; }
        public string Trw { get; set; }
        public string Mcquay { get; set; }
        public string Spicer { get; set; }
        public string Patyoung { get; set; }
        public string Monroe { get; set; }
        public string Leacree { get; set; }
        public string Dorman { get; set; }
        public string ConiSeal { get; set; }
        public string Ng { get; set; }
        public string Wheels { get; set; }
        public string Bca { get; set; }
        public string Skf { get; set; }
        public string Timken { get; set; }
        public string Gates { get; set; }
        public string Dayco { get; set; }
        public string Goodyear { get; set; }
        public string Bmp { get; set; }
        public string Wix { get; set; }
        public string Fram { get; set; }
        public string Purolator { get; set; }
        public string ChampSrvc { get; set; }
        public string ChampLube { get; set; }
        public string Pennzoil { get; set; }
        public string Qkerstate { get; set; }
        public string Hastings { get; set; }
        public string Atp { get; set; }
        public string Atlas { get; set; }
        public string ChampAuto { get; set; }
        public string Kralinator { get; set; }
        public string Mighty { get; set; }
        public string Motorcraft { get; set; }
        public string Prtsmaster { get; set; }
        public string Asc { get; set; }
        public string Gmb { get; set; }
        public string Ptc { get; set; }
        public string Airtex { get; set; }
        public string Bosch { get; set; }
        public string Satisfied { get; set; }
        public string Iapexpert { get; set; }
        public string Wiper { get; set; }
        public string Gabriel { get; set; }
        public string Kyb { get; set; }
        public string Acdelco { get; set; }
        public string Ucdpads { get; set; }
        public string Mdpads { get; set; }
        public string Cbs { get; set; }
        public string Brkshoes { get; set; }
        public string Brkpads { get; set; }
        public string Collins { get; set; }
        public string Worldbrakecorp { get; set; }
        public string Safeline { get; set; }
        public string Awceramic { get; set; }
        public string Autounlimited { get; set; }
        public string Brook { get; set; }
        public string Tinker { get; set; }
        public string TruStar { get; set; }
        public string Dura { get; set; }
        public string Lester { get; set; }
        public string Wai { get; set; }
        public string Eclipse { get; set; }
        public string Ntk { get; set; }
        public string Tyc { get; set; }
        public string Partslink { get; set; }
        public string Carpart { get; set; }
        public string Ape { get; set; }
        public string Brockauto { get; set; }
        public string Rpt { get; set; }
        public string Atl { get; set; }
        public string Bbp { get; set; }
        public string Abs { get; set; }
        public string Btk { get; set; }
        public string Tra { get; set; }
        public string Val { get; set; }
        public string Kaptemp { get; set; }
        public string Walker { get; set; }
        public string Suncore { get; set; }
        public string Mgi { get; set; }
        public string Strutmaster { get; set; }
        public string Specd { get; set; }
        public string Spyder { get; set; }
        public string RayR { get; set; }
        public string Koolvue { get; set; }
        public string Jci { get; set; }
        public string Bsp { get; set; }
        public string Nat { get; set; }
        public string Vision { get; set; }
        public string BlueStreak { get; set; }
        public string Pucheng { get; set; }
        public string Rainx { get; set; }
        public string Wiperelement { get; set; }
        public string CalLidz { get; set; }
        public string FelPro { get; set; }
        public string Agnaupc { get; set; }
        public string Polyway { get; set; }
        public string Fpd { get; set; }
        public string BwdAutomotive { get; set; }
        public string Anco { get; set; }
        public string Wells { get; set; }
        public string Ilink { get; set; }
        public string Philips { get; set; }
        public string Sensen { get; set; }
        public string Syl { get; set; }
        public string Dpi { get; set; }
        public string Adt { get; set; }
        public string Exedy { get; set; }
    }
}
